# Site settings
title: Lytekk
header-img: img/home-bg.jpg
email: nguyen.chriss@gmail.com
copyright_name: Lytekk/MKS
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://lytekk.github.io"
linkedin_username: nguyenchriss
github_username:  Lytekk
email_username:  nguyen.chriss@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]

